# FuryMesh Configuration

# Server configuration
server:
  host: "localhost"
  port: 8080

# Storage configuration
storage:
  # Base directory for storing files and metadata
  base_dir: "~/.furymesh"
  # Working directory for temporary files
  work_dir: "~/.furymesh/work"
  # Default chunk size in bytes (1MB)
  chunk_size: 1048576
  # Maximum storage size in bytes (10GB)
  max_storage: 10737418240
  # Time to live for expired files in hours (168 hours = 7 days)
  file_ttl: 168

# Transfer configuration
transfer:
  # Timeout for data requests in seconds
  request_timeout: 30
  # Maximum number of retries for failed transfers
  max_retries: 3
  # Maximum number of concurrent transfers
  concurrent_transfers: 5
  # Maximum bandwidth usage in bytes per second (0 = unlimited)
  max_bandwidth: 0

# WebRTC configuration
webrtc:
  # STUN servers for NAT traversal
  stun_servers:
    - "stun:stun.l.google.com:19302"
    - "stun:stun1.l.google.com:19302"
  # TURN servers for fallback relay
  turn_servers: []
  # ICE candidate types to use (host, srflx, prflx, relay)
  ice_candidate_types:
    - "host"
    - "srflx"
    - "relay"

compression:
  enabled: true
  algorithm: "zstd"

logging:
  level: "info"

api:
  port: 8080
