// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fury

import "strconv"

type MessageType int8

const (
	MessageTypeFileChunk      MessageType = 0
	MessageTypeFileMetadata   MessageType = 1
	MessageTypeChunkRequest   MessageType = 2
	MessageTypeTransferStatus MessageType = 3
	MessageTypeErrorMessage   MessageType = 4
)

var EnumNamesMessageType = map[MessageType]string{
	MessageTypeFileChunk:      "FileChunk",
	MessageTypeFileMetadata:   "FileMetadata",
	MessageTypeChunkRequest:   "ChunkRequest",
	MessageTypeTransferStatus: "TransferStatus",
	MessageTypeErrorMessage:   "ErrorMessage",
}

var EnumValuesMessageType = map[string]MessageType{
	"FileChunk":      MessageTypeFileChunk,
	"FileMetadata":   MessageTypeFileMetadata,
	"ChunkRequest":   MessageTypeChunkRequest,
	"TransferStatus": MessageTypeTransferStatus,
	"ErrorMessage":   MessageTypeErrorMessage,
}

func (v MessageType) String() string {
	if s, ok := EnumNamesMessageType[v]; ok {
		return s
	}
	return "MessageType(" + strconv.FormatInt(int64(v), 10) + ")"
}
